name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Echo
          run: echo "${GITHUB_REF}"    