name: Build and Release countingbook app

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Echo some variables
          run: echo "${GITHUB_REF} ${GITHUB_OUTPUT} ${{ github.ref_name }}"
        - name: Set up Node.js environment
          uses: actions/setup-node@v4
          with:
              node-version: '22'
        - run: echo "before" && ls -la
        - name: Checkout code
          uses: actions/checkout@v5
        - run: echo "after" && ls -la